import { Inter } from 'next/font/google';
import './globals.css';
import NextAuthProvider from './components/NextAuthProvider';
import { getServerSession } from 'next-auth/next';
import { options } from './api/auth/[...nextauth]/option';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={inter.className}>{children}</body>
      </NextAuthProvider>
    </html>
  );
}
